services:
  - type: web
    name: mon-app-php
    runtime: php
    rootDirectory: .
    buildCommand: ""
    startCommand: php -S 0.0.0.0:$PORT
    envVars:
      - key: PHP_VERSION
        value: 8.2